name: Testing github actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Echoing github actions
        run: echo "Github action is alive"
